version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: "1.16.5"
      MODPACK: "https://github.com/phantomic12/temp1/releases/download/dfvx/server.zip"
    tty: true
    stdin_open: true
    restart: unless-stopped