name: Test Modpack

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: docker up
      run: docker-compose up -d

    - name: Run Server
      timeout-minutes: 75
      run: sudo sh start.sh
